/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef sample_CONSTANTS_H
#define sample_CONSTANTS_H

#include "sample_types.h"

namespace sample {

class sampleConstants {
 public:
  sampleConstants();

};

extern const sampleConstants g_sample_constants;

} // namespace

#endif
