/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "control4_constants.h"

namespace c4 {

const control4Constants g_control4_constants;

control4Constants::control4Constants() {
}

} // namespace

