/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef control4_CONSTANTS_H
#define control4_CONSTANTS_H

#include "control4_types.h"

namespace c4 {

class control4Constants {
 public:
  control4Constants();

};

extern const control4Constants g_control4_constants;

} // namespace

#endif
